apiVersion: v1
kind: Pod
metadata:
  name: debian-test
  namespace: zebflow-test
  labels:
    app.kubernetes.io/name: debian-test
    app.kubernetes.io/part-of: zebflow-test
spec:
  automountServiceAccountToken: false
  restartPolicy: Always
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  containers:
    - name: debian
      image: debian:bookworm-slim
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-lc", "sleep infinity"]
