apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: zebflow
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  default-password: {{ .Values.secrets.defaultPassword | b64enc | quote }}
